---
- name: Configure app server
  hosts: app_servers
  become: yes

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Nginx web server
      apt:
        name: nginx
        state: present
      notify:
        - Start Nginx

    - name: Install Java (OpenJDK 17)
      apt:
        name: openjdk-17-jdk
        state: present

  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
